.TH GENEWEB 1 "2000 July 22"
.UC 4
.SH NAME
consang \- Computer Genealogical Consanguinities
.SH SYNOPSIS
.B consang
[
.I file
] 
.br
.SH DESCRIPTION
.I consang
calculates the consanguinities in the
.IR E Geneweb
database passed at the command line.
.br
The displaying of consanguinities is done when consulting the
database, in the personal records, and while computing
relationships.
.PP
The primary documentation of
.I consang
is in the wiki page
.B https://geneweb.tuxfamily.org/wiki/man#Command_lines_operation
.PP

