.TH gwb2ged 1 "2002 October 20"
.UC 4
.SH NAME
gwb2ged \- Dump a GeneWeb database to a GEDCOM File
.SH SYNOPSIS
.B gwb2ged
[
.I \<base\>
] [
.I options
]
.br
.SH DESCRIPTION
.I gwb2ged
dumps a
.IR GeneWeb
database to a GEDCOM file.
.PP
The primary documentation of
.I gwb2ged 
is in the wiki page
.B https://geneweb.tuxfamily.org/wiki/man#Command_lines_operation
.PP
.SH OPTIONS
.PP
If both options -a and -d are used, intersection is assumed.
.br
If several options -s are used, union is assumed.
.TP 8
.B \-help
command-line help
.TP
.B \-o <ged>
output file name (default: a.ged)
.TP
.B \-charset [ASCII|ANSEL]:
Set charset. Default is ASCII. Warning: value ANSEL works correctly only
on iso-8859-1 encoded databases.
.TP
.B \-o <ged> 
output file name (default: a.ged)
.TP
.B \-mem
save memory space, but slower
.TP
.B \-a "<1st_name>" [num] "<surname>"
select ancestors of
.TP
.B \-d "<1st_name>" [num] "<surname>" 
select descendants of
.TP
.B \-aws "<1st_name>" [num] "<surname>"
select ancestors with siblings
.TP
.B \-s "<surname>"
select this surname (option usable several times)
.TP
.B \-nsp
no spouses' parents (for options -s and -d)
.TP
.B \-nn
no (database) notes
.TP
.B \-c <num>
When a person is born less than <num> years ago, it is not exported unless
it is Public. All the spouses and descendants are also censored.

