.TH gwc2 1 "2007 September 12th"
.SH NAME
gwc \- Create a GeneWeb database
.SH SYNOPSIS
.B gwc2
[
.I options
] [
.I files
]
.br
.SH DESCRIPTION
.I gwc
creates a database for use by 
.IR GeneWeb.
.PP
It is a new database system, different from the ones built by the command
gwc.
.PP
.SH OPTIONS
.PP
.TP 8
.B \-help
command-line help
.TP
.B \-o <file>
output database (default: a.gwb)
.TP
.BI \-c
only compiling
.TP
.BI \-f
Remove database if already existing
.TP
.BI \-stats
Print statistics
.TP
.BI \-nc
No consistency check
.TP
.BI \-cg
Compute consanguinity
.TP
.BI \-sep
Separate all persons in next file
.TP
.BI \-sh  \f\<int\>\f
Shift all persons numbers in next files
.TP
.BI \-ds 
set the source field for persons and families without source data
.TP
.BI \-mem  
Save memory, but slower
.TP
.BI \-nolock  
do not lock database
.PP
.SH SEE ALSO
gwc(1)

