.TH gwsetup 1 "2005 November 28th"
.SH NAME
gwsetup \- Interactive interface to Geneweb databases management
.SH SYNOPSIS
.B gwsetup
[
.I options
]
.br
.SH DESCRIPTION
.I gwsetup
helps in
.IR GeneWeb
databases management.
.PP
The primary documentation of
.I gwsetup
is in the wiki page
.B https://geneweb.tuxfamily.org/wiki/man#Command_lines_operation
.PP
.SH OPTIONS
.PP
.TP 8
.B \-help
command-line help
.TP
.B \-lang <string>
default language
.TP
.B \-daemon
use as a Unix daemon
.TP
.B \-p <port>
select a port number (default=2316)
.TP
.B \-only <file>
path to the file containing the IP address of the authorized host
.TP
.B \-log <file>
redirect log trace to this file.
.TP
.B \-gd <dir>
path of the geneweb share directory


