  $ gwd --check --plugin u:../../plugins/cgl
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) cgl...
  [DEBUG][GWD]: End of check mode.

  $ gwd --check --plugin f:../../plugins/cgl
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) cgl...
  [DEBUG][GWD]: End of check mode.

  $ gwd --check --plugin uf:../../plugins/cgl
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) cgl...
  [DEBUG][GWD]: End of check mode.

  $ gwd --check --plugins ../../plugins
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) cgl...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) export...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) lib_show...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) fixbase...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) forum...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) jingoo...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) gwxjg...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) no_index...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = false) xhtml...
  [DEBUG][GWD]: End of check mode.

  $ gwd --check --plugins u:../../plugins
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) cgl...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) export...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) lib_show...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) fixbase...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) forum...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) jingoo...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) gwxjg...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) no_index...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = false) xhtml...
  [DEBUG][GWD]: End of check mode.

  $ gwd --check --plugins f:../../plugins
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) cgl...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) export...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) lib_show...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) fixbase...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) forum...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) jingoo...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) gwxjg...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) no_index...
  [DEBUG][GWD]: Loading plugin (unsafe = false, forced = true) xhtml...
  [DEBUG][GWD]: End of check mode.

  $ gwd --check --plugins uf:../../plugins
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) cgl...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) export...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) lib_show...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) fixbase...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) forum...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) jingoo...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) gwxjg...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) no_index...
  [DEBUG][GWD]: Loading plugin (unsafe = true, forced = true) xhtml...
  [DEBUG][GWD]: End of check mode.

  $ gwd --check --plugin ../../plugins/foo
  [DEBUG][GWD]: Starting the HTTP server...
  [ERROR][GWD]: "../../plugins/foo" is not a plugin directory.
  [DEBUG][GWD]: End of check mode.

  $ mkdir -p ./foo/bar && gwd --check --plugins ./foo; rm -Rf foo
  [DEBUG][GWD]: Starting the HTTP server...
  [DEBUG][GWD]: End of check mode.
