  $ gwd -check -plugin -unsafe ../../plugins/cgl
  [DEBUG] Loading plugin (unsafe = true, forced = false) cgl...

  $ gwd -check -plugin -force ../../plugins/cgl
  [DEBUG] Loading plugin (unsafe = false, forced = true) cgl...

  $ gwd -check -plugin -unsafe -force ../../plugins/cgl
  [DEBUG] Loading plugin (unsafe = true, forced = true) cgl...

  $ gwd -check -plugins ../../plugins
  [DEBUG] Loading plugin (unsafe = false, forced = false) cgl...
  [DEBUG] Loading plugin (unsafe = false, forced = false) export...
  [DEBUG] Loading plugin (unsafe = false, forced = false) lib_show...
  [DEBUG] Loading plugin (unsafe = false, forced = false) fixbase...
  [DEBUG] Loading plugin (unsafe = false, forced = false) forum...
  [DEBUG] Loading plugin (unsafe = false, forced = false) jingoo...
  [DEBUG] Loading plugin (unsafe = false, forced = false) gwxjg...
  [DEBUG] Loading plugin (unsafe = false, forced = false) no_index...
  [DEBUG] Loading plugin (unsafe = false, forced = false) xhtml...

  $ gwd -check -plugins -unsafe ../../plugins
  [DEBUG] Loading plugin (unsafe = true, forced = false) cgl...
  [DEBUG] Loading plugin (unsafe = true, forced = false) export...
  [DEBUG] Loading plugin (unsafe = true, forced = false) lib_show...
  [DEBUG] Loading plugin (unsafe = true, forced = false) fixbase...
  [DEBUG] Loading plugin (unsafe = true, forced = false) forum...
  [DEBUG] Loading plugin (unsafe = true, forced = false) jingoo...
  [DEBUG] Loading plugin (unsafe = true, forced = false) gwxjg...
  [DEBUG] Loading plugin (unsafe = true, forced = false) no_index...
  [DEBUG] Loading plugin (unsafe = true, forced = false) xhtml...

  $ gwd -check -plugins -force ../../plugins
  [DEBUG] Loading plugin (unsafe = false, forced = true) cgl...
  [DEBUG] Loading plugin (unsafe = false, forced = true) export...
  [DEBUG] Loading plugin (unsafe = false, forced = true) lib_show...
  [DEBUG] Loading plugin (unsafe = false, forced = true) fixbase...
  [DEBUG] Loading plugin (unsafe = false, forced = true) forum...
  [DEBUG] Loading plugin (unsafe = false, forced = true) jingoo...
  [DEBUG] Loading plugin (unsafe = false, forced = true) gwxjg...
  [DEBUG] Loading plugin (unsafe = false, forced = true) no_index...
  [DEBUG] Loading plugin (unsafe = false, forced = true) xhtml...

  $ gwd -check -plugins -unsafe -force ../../plugins
  [DEBUG] Loading plugin (unsafe = true, forced = true) cgl...
  [DEBUG] Loading plugin (unsafe = true, forced = true) export...
  [DEBUG] Loading plugin (unsafe = true, forced = true) lib_show...
  [DEBUG] Loading plugin (unsafe = true, forced = true) fixbase...
  [DEBUG] Loading plugin (unsafe = true, forced = true) forum...
  [DEBUG] Loading plugin (unsafe = true, forced = true) jingoo...
  [DEBUG] Loading plugin (unsafe = true, forced = true) gwxjg...
  [DEBUG] Loading plugin (unsafe = true, forced = true) no_index...
  [DEBUG] Loading plugin (unsafe = true, forced = true) xhtml...

