  $ gwd -check -plugin -unsafe ../../plugins/cgl
  [DEBUG] Loading plugin cgl...

  $ gwd -check -plugin -force ../../plugins/cgl
  [DEBUG] Loading plugin cgl...

  $ gwd -check -plugin -unsafe -force ../../plugins/cgl
  [DEBUG] Loading plugin cgl...

  $ gwd -check -plugins ../../plugins
  [DEBUG] Loading plugin cgl...
  [DEBUG] Loading plugin export...
  [DEBUG] Loading plugin lib_show...
  [DEBUG] Loading plugin fixbase...
  [DEBUG] Loading plugin forum...
  [DEBUG] Loading plugin jingoo...
  [DEBUG] Loading plugin gwxjg...
  [DEBUG] Loading plugin no_index...
  [DEBUG] Loading plugin xhtml...

  $ gwd -check -plugins -unsafe ../../plugins
  [DEBUG] Loading plugin cgl...
  [DEBUG] Loading plugin export...
  [DEBUG] Loading plugin lib_show...
  [DEBUG] Loading plugin fixbase...
  [DEBUG] Loading plugin forum...
  [DEBUG] Loading plugin jingoo...
  [DEBUG] Loading plugin gwxjg...
  [DEBUG] Loading plugin no_index...
  [DEBUG] Loading plugin xhtml...

  $ gwd -check -plugins -force ../../plugins
  [DEBUG] Loading plugin cgl...
  [DEBUG] Loading plugin export...
  [DEBUG] Loading plugin lib_show...
  [DEBUG] Loading plugin fixbase...
  [DEBUG] Loading plugin forum...
  [DEBUG] Loading plugin jingoo...
  [DEBUG] Loading plugin gwxjg...
  [DEBUG] Loading plugin no_index...
  [DEBUG] Loading plugin xhtml...

  $ gwd -check -plugins -unsafe -force ../../plugins
  [DEBUG] Loading plugin cgl...
  [DEBUG] Loading plugin export...
  [DEBUG] Loading plugin lib_show...
  [DEBUG] Loading plugin fixbase...
  [DEBUG] Loading plugin forum...
  [DEBUG] Loading plugin jingoo...
  [DEBUG] Loading plugin gwxjg...
  [DEBUG] Loading plugin no_index...
  [DEBUG] Loading plugin xhtml...

