(* ocaml ./configure.ml *)
#use "topfind"

#require "unix"

let installed pkg = 0 = Sys.command ("ocamlfind query -qo -qe " ^ pkg)
let errmsg = "usage: " ^ Sys.argv.(0) ^ " [options]"

let speclist =
  [
    ("--sosa-legacy", Arg.Unit ignore, " Use legacy Sosa module implementation");
    ( "--sosa-zarith",
      Arg.Unit ignore,
      " Use Sosa module implementation based on `zarith` library" );
    ("--syslog", Arg.Unit ignore, " Log gwd errors using syslog");
    ("--gwd-caching", Arg.Unit ignore, " Enable database preloading (Unix-only)");
  ]
  |> List.sort compare |> Arg.align

let () =
  Arg.parse speclist failwith errmsg;
  let os_type, ext, rm =
    match
      let p = Unix.open_process_in "uname -s" in
      let line = input_line p in
      close_in p;
      line
    with
    | ("Linux" | "Darwin" | "FreeBSD") as os_type -> (os_type, "", "/bin/rm -f")
    | _ -> ("Win", ".exe", "rm -f")
  in
  let ch = open_out "Makefile.config" in
  let writeln s = output_string ch @@ s ^ "\n" in
  let var name value = writeln @@ name ^ "=" ^ value in
  writeln @@ "# This file is generated by " ^ Sys.argv.(0) ^ ".";
  var "OS_TYPE" os_type;
  var "RM" rm;
  var "EXT" ext;
  close_out ch
