# $Id: Makefile.Mac,v 1.4 2000-05-03 12:33:35 ddr Exp $

#include ::tools:Makefile.Mac

OCAMLI =
OBJS = wserver.cmo

all ÄÄ {OBJS}
    echo

depend Ä
    ::tools:camlp4_depend.mpw {OCAMLI} Å.mlÅ > Makefile.Mac.depend
