all out opt Ä LICENSE.htm

clean Ä
    delete -y LICENSE.htm

LICENSE.htm Ä ::LICENSE
   begin
     echo '<head><title>License</title></head><body><pre>'
     catenate ::LICENSE
     echo '</pre></body>'
   end > LICENSE.htm
