include $(PIQI_ROOT)/piqilib/Makefile.piqi_common


PIQI_SOURCES_EXTENDED = \
	piqi_ext.ml \
	piqi_func.ml \
	piqilib.ml \
	piqi_pp.ml \


PIQI_SOURCES_TAIL += $(PIQI_SOURCES_EXTENDED)


$(PIQI_SOURCES_EXTENDED): % : $(PIQI_ROOT)/piqilib/%
	ln -s $< $@

