ROOT := ../..

INCDIRS := $(ROOT)/src
ALL_EXE := gwRemoveImgGallery gwBaseCompatiblePlus gwFixDateText gwExportAscCSV
EVERYTHING_EXE := gwFixAddEvent gwMostAsc
LIBS = unix

include $(ROOT)/tools/Makefile.config
