ROOT := ../..

INCDIRS := $(ROOT)/src
ALL_EXE := gwFixBase gwFixFromFile gwFixFromFileDomicile gwFixFromFileAlias \
           gwFixBurial gwFixEvtSrc gwFixColon gwFindCpl gwFixY
LIBS = $(LIBUNIX) str gramlib
LINKFLAGS = $(LINKUNIX) -I $(CAMLP5D)

include $(ROOT)/tools/Makefile.config
