ROOT := ../..

INCDIRS := $(ROOT)/src
ALL_EXE := gwFixBase gwFixFromFile gwFixFromFileDomicile gwFixFromFileAlias \
           gwFixBurial gwFixEvtSrc gwFixColon gwFindCpl gwFixY
LIBS = unix str gramlib
LINKFLAGS = -I $(CAMLP5D)

include $(ROOT)/tools/Makefile.common
