ROOT := ..

ALL_EXE := transitive_depend

include $(ROOT)/tools/Makefile.config

transitive_depend: $(.DEFAULT_GOAL)
transitive_depend.opt: transitive_depend.cmx
transitive_depend.out: transitive_depend.cmo
