(*
   Copyright 2009, 2010, 2011 Anton Lavrik

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*)

(* Runtime support for JSON-XML-Protobuf-Piq serialization
 *
 * This module is used by OCaml modules generated by "piqic ocaml-ext" Piqi
 * compiler.
 *)


type input_format = [ `json | `pb | `piq | `wire | `xml ]

type output_format = [ input_format | `json_pretty | `xml_pretty ]

type piqtype

type options


val init_piqi : string list -> unit

val find_piqtype : string -> piqtype

val make_options:
        ?pretty_print:bool ->
        ?json_omit_null_fields:bool ->
        unit -> options

val convert:
  ?opts:options ->
  piqtype -> input_format -> output_format -> string -> string

