name: Debug Workflow

on:
  push:
    branches: [ged2gwb]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment
        run: |
          echo "=== Current branch ==="
          git branch --show-current

          echo "=== Files changed in last commit ==="
          git diff --name-only HEAD~1 HEAD || echo "No previous commit"

          echo "=== Directory structure ==="
          find . -name "*.yml" -o -name "*.json" -o -name "*.py" | grep -E "(test|python|github)" | sort

          echo "=== Test files ==="
          ls -la test/ || echo "No test directory"
          ls -la test/scena/ || echo "No test/scena directory"

          echo "=== Python files ==="
          ls -la python/ || echo "No python directory"
          echo "=== GitHub workflows ==="
          ls -la .github/workflows/
