name: GeneWeb Docker

on:
  push:
  #   branches:
  #     - "main"
  #   tags:
  #     - "v*"
  # pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - target: gwd
            image: halbaroth/gwd
          - target: gwsetup
            image: halbaroth/gwsetup

    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      target: ${{ matrix.target }}
      meta-images: ${{ matrix.image }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
        type=semver,pattern={{version}}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
