name: GeneWeb Releases
on:
  push:

env:
  OPAMYES: true
  TAG: ${{ github.ref_name }}

jobs:
  build-dynamic:
    strategy:
      matrix:
        # os: [ubuntu-latest, ubuntu-26.04-arm, macos-latest, windows-latest]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install Perl dependencies
        if: runner.os == 'Windows'
        shell: bash
        run: |
          curl -fsSL https://cpanmin.us | perl - --notest IPC::System::Simple String::ShellQuote
          opam install --assume-depexts \
            conf-perl-ipc-system-simple \
            conf-perl-string-shellquote

      - name: Install Microsoft MSBuild
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v3

      - name: Install WiX Toolset
        if: runner.os == 'Windows'
        run: |
          dotnet tool install --global wix --version 6.0.2
          wix.exe extension add WixToolset.Util.wixext/6.0.2
          wix.exe extension add WixToolset.UI.wixext/6.0.2

      - name: Install GeneWeb dependencies
        run: make deps

      - name: Build GeneWeb bundle
        run: opam exec -- make bundle

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: geneweb-${{ runner.os }}-${{ runner.arch }}-${{ env.TAG }}-dynamic
          path: geneweb-*-*-*-*.*
          archive: false

  # build-static:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, ubuntu-26.04-arm]
  #
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v7
  #
  #     - name: Build GeneWeb artifact
  #       run: make static
  #
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: geneweb-${{ runner.os }}-${{ runner.arch }}-${{ env.TAG }}-static
  #         path: geneweb-*-*-*-*.*
  #         archive: false
  #
  # opam-install:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest]
  #
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v7
  #
  #     - name: Setup Ocaml
  #       uses: ocaml/setup-ocaml@v3
  #       with:
  #         ocaml-compiler: 5
  #
  #     - name: Install geneweb-compat
  #       run: opam install ./geneweb-compat.opam
  #
  #     - name: Install geneweb-http
  #       run: opam install ./geneweb-http.opam
  #
  #     - name: Install geneweb
  #       run: opam install ./geneweb.opam
  #
  #     - name: Install geneweb-plugins
  #       run: opam install ./geneweb-plugins.opam
  #
  #     - name: Install geneweb-rpc
  #       run: opam install ./geneweb-rpc.opam
  #
  #     - name: Check binaries
  #       run: opam exec -- gwd --check
  #
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: [build-dynamic, build-static, opam-install]
  #   permissions:
  #     contents: write
  #
  #   steps:
  #     - name: Retrieve artifacts
  #       uses: actions/download-artifact@v8
  #
  #     - name: Display structure of downloaded files
  #       run: ls -R
  #
  #     - name: Publish release artifacts
  #       uses: softprops/action-gh-release@v3
  #       if: github.ref_type == 'tag'
