name: Simple Trigger Test

on:
  push:
    branches: [ged2gwb]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test basic functionality
        run: |
          echo "🎉 GitHub Actions is working!"
          echo "Current branch: $(git branch --show-current)"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"

      - name: List files
        run: |
          echo "=== Repository structure ==="
          find . -name "*.json" -o -name "*.py" -o -name "*.yml" | head -20

      - name: Check Python
        run: |
          python3 --version
          pip --version
